### ISSUE TITLE
MacOS brew installation support?

### ISSUE THREAD

**Issue by hrstoyanov** [router-for-me/CLIProxyAPI#79]
Awesome project! Any way to integrate brew install for MacOS (also Linus) in the git actions?

**Comment by luispater** [comment]
Let me do some research. Thank you for your suggestion.

**Comment by luispater** [comment]
Done.

https://github.com/Homebrew/homebrew-core/pull/247024

**Comment by hrstoyanov** [comment]
Great! I still do not see it in the installation section of  README.md?
